### ISSUE TITLE
Weirzard Academy [65000013]

### ISSUE THREAD

**Issue by Aubertin** [0x4261756D/CCS_scripts#15]
Neuer Effect: Weirzard monsters cannot be targeted for attacks. Twice per turn, if a “Weirzard” monster(s) is Summoned: You can shuffle 1 of your banished Spells into your Deck. Once per turn: You can reveal any number of Spells in your hand, including 1 “Weirzard” Spell, shuffle them into your Deck, then draw the same number of cards.

+Neues Bild

**Comment by Rundas01** [comment]
Neues pic per PR hochladen bidde
