### ISSUE TITLE
Weirzard Wogian 

### ISSUE THREAD

**Issue by Aubertin** [0x4261756D/CCS_scripts#19]
You can shuffle 1 Spell from your GY into your Deck, then banish 1 Spell from your Deck; Special Summon 1 “Weirzard” monster from your hand, but its effects are negated. If a Spell card is banished from your Deck while this card is in your GY: You can add 1 “Weirzard” monster from your GY to your hand. If a “Weirzard” card(s) would be destroyed by battle or card effect, you can banish 1 Spell from your Deck instead. You can only use each effect of “Weirzard Wogian” once per turn.

neuer effekt script bitte ändern :)

**Comment by Rundas01** [comment]
Was ein Krampf
