### ISSUE TITLE
Cursed Bamboo Sword Bug mit Katango

### ISSUE THREAD

**Issue by 0x4261756D** [0x4261756D/CCS_scripts#24]
**Steps to reproduce:**

1. Control Katango, Cursed Bamboo Swordsman
2. Equip with Cursed Bamboo Sword
3. Activate Cursed Bamboo Sword targetting Katango

*Erwartet:*
Kein Fehler, Katango geht auf die Hand.

*Was wirklich passiert:*
Katango geht zwar auf die Hand, allerdings mit einer Fehlermeldung ([Script Error]: [string "c42199039.lua"]:50: attempt to index a nil value (local 'ec')), da das Monster nicht mehr auf dem Feld ist.

**Comment by Rundas01** [comment]
Das liegt nicht an Katango sondern CBS

**Comment by Rundas01** [comment]
Hab nen PR offen, das Problem wird gelöst sein, sobald dieser gemerged ist.
