### ISSUE TITLE
Wrong archetype setcode

### ISSUE THREAD

**Issue by MoonBurst** [0x4261756D/CCS_scripts#28]
Archlord Ixchel id 64000106 claims it is a Lightray archetype card. This is not the case.
Archlord Ukoback id 64000110 shares the same issue.
Official card Archlord Kristya does NOT claim to be a Lightray, suggesting this is not simply a translation error.

**Comment by 0x4261756D** [comment]
Should be fixed now (see commit 6130e80d0aab642ac24f0663e425fb75ea4f045b)
