### ISSUE TITLE
Meteorite Kicking Dinosaur

### ISSUE THREAD

**Issue by Aubertin** [0x4261756D/CCS_scripts#6]
Karte hat einen neuen Effekt text
"2 Level 4 or lower Dinosaur monsters with the same Level
If this card is Link Summoned: You can destroy 1 monster from your Deck. You can only use this effect of “Meteorite Kicking Dinosaur” once per turn. If a Dinosaur monster is Summoned: Destroy this card, then destroy 1 Spell/Trap from your Deck."

script sollte dementsprechend angepasst werden

neues Link Rating "Link 2"
Atk 1500
Link Pfeile nach oben und nach unten
bild wurde weitergeleitet

**Comment by Rundas01** [comment]
Script kannst du selber ändern :D
Das gibt Übung

**Comment by Aubertin** [comment]
wenn ich keine Ahnung hab was zu tun ist hilfts nicht xD

Segal z.b. zieht immernoch ne karte
